server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercesdb
    username: ecommerce_user
    password: ecommerce123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: staging
